services:
  dbservice:
    image: postgres:17
    volumes:
      - slidetap_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=slidetap
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d slidetap"]
      interval: 5s
      timeout: 5s
      retries: 10

  dbmigrate:
    env_file: .env
    environment:
      SLIDETAP_DBURI: postgresql://user:password@dbservice:5432/slidetap
    build:
      context: ../slidetap-app
      dockerfile: dockerfiles/taskservice.Dockerfile
    working_dir: /app/slidetap
    command: >
      sh -c "alembic upgrade head &&
             slidetap-task-init-schema"
    restart: "no"
    depends_on:
      dbservice:
        condition: service_healthy

  taskservice:
    env_file: .env
    environment:
      SLIDETAP_STORAGE: /storage
      SLIDETAP_DBURI: postgresql://user:password@dbservice:5432/slidetap
      SLIDETAP_WEBAPP_URL: https://${SLIDETAP_SERVERNAME}:${SLIDETAP_PORT}
    build:
      context: ../slidetap-app
      dockerfile: dockerfiles/taskservice.Dockerfile
    volumes:
      - ${SLIDETAP_STORAGE}:/storage:rw
    depends_on:
      dbmigrate:
        condition: service_completed_successfully

  appservice:
    env_file: .env
    environment:
      SLIDETAP_STORAGE: /storage
      SLIDETAP_DBURI: postgresql://user:password@dbservice:5432/slidetap
      SLIDETAP_WEBAPP_URL: https://${SLIDETAP_SERVERNAME}:${SLIDETAP_PORT}
      SLIDETAP_APIPORT: ${SLIDETAP_APIPORT}
    build:
      context: ../slidetap-app
      dockerfile: dockerfiles/webservice.Dockerfile
    volumes:
      - ${SLIDETAP_STORAGE}:/storage:rw
    depends_on:
      dbmigrate:
        condition: service_completed_successfully

  webserver:
    env_file: .env
    build:
      context: ../slidetap-client
      dockerfile: dockerfiles/webserver.Dockerfile
    ports:
      - ${SLIDETAP_PORT}:${SLIDETAP_PORT}
    volumes:
      - ${SLIDETAP_SSL_CERTIFICATE_FOLDER}:/certs:ro
    depends_on:
      appservice:
        condition: service_started

volumes:
  slidetap_postgres_data:
