services:
  dbservice:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=slidetap

  brokerservice:
    image: rabbitmq:3
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  taskservice:
    env_file: .env
    environment:
      SLIDETAP_STORAGE: /storage
      SLIDETAP_DBURI: postgresql://user:password@dbservice:5432/slidetap
      SLIDETAP_BROKER_URL: amqp://user:password@brokerservice:5672
      SLIDETAP_WEBAPPURL: https://${SLIDETAP_SERVERNAME}:${SLIDETAP_PORT}
      SLIDETAP_TASK_APP: ${SLIDETAP_TASK_APP}
    build:
      context: ./slidetap-app
      dockerfile: dockerfiles/taskservice.Dockerfile
    volumes:
      - ${SLIDETAP_STORAGE}:/storage:rw
    depends_on:
      brokerservice:
        condition: service_started
      dbservice:
        condition: service_started

  appservice:
    env_file: .env
    environment:
      SLIDETAP_STORAGE: /storage
      SLIDETAP_DBURI: postgresql://user:password@dbservice:5432/slidetap
      SLIDETAP_WEBAPPURL: https://${SLIDETAP_SERVERNAME}:${SLIDETAP_PORT}
      SLIDETAP_BROKER_URL: amqp://user:password@brokerservice:5672
      SLIDETAP_APIPORT: ${SLIDETAP_APIPORT}
      SLIDETAP_WEB_APP_CREATOR: ${SLIDETAP_WEB_APP_CREATOR}
    build:
      context: ./slidetap-app
      dockerfile: dockerfiles/appservice.Dockerfile
    volumes:
      - ${SLIDETAP_STORAGE}:/storage:rw
    depends_on:
      brokerservice:
        condition: service_started
      dbservice:
        condition: service_started

  webserver:
    env_file: .env
    build:
      context: ./slidetap-client
      dockerfile: dockerfiles/webserver.Dockerfile
    ports:
      - ${SLIDETAP_PORT}:${SLIDETAP_PORT}
    volumes:
      - ${SLIDETAP_SSL_CERTIFICATE_FOLDER}:/certs:ro
    depends_on:
      appservice:
        condition: service_started

volumes:
  postgres_data:
