set FLASK_APP=slidetap/apps/example/app
set FLASK_RUN_PORT=5001
set FLASK_DEBUG=true
set FLASK_TESTING=true
set SLIDES_SECRET_KEY=DEVELOP
set SLIDES_WEBAPPURL=http://localhost:13000
set SLIDES_STORAGE=C:\temp\slidetap
set SLIDES_DBURI=sqlite:///C:/temp/slidetap/db.sqlite
set SLIDES_KEEPALIVE=1800
set SLIDES_ENFORCE_HTTPS=false
flask run --host=0.0.0.0
