from enum import Enum


class ImageStatus(Enum):
    NOT_STARTED = 1
    DOWNLOADING = 2
    DOWNLOADING_FAILED = 3
    DOWNLOADED = 4
    PRE_PROCESSING = 5
    PRE_PROCESSING_FAILED = 6
    PRE_PROCESSED = 7
    POST_PROCESSING = 8
    POST_PROCESSING_FAILED = 9
    POST_PROCESSED = 10
    # COMPLETED = 11
