from enum import Enum


class ProjectStatus(Enum):
    INITIALIZED = 1
    METADATA_SEARCHING = 2
    METEDATA_SEARCH_COMPLETE = 3
    IMAGE_PRE_PROCESSING = 4
    IMAGE_PRE_PROCESSING_COMPLETE = 5
    IMAGE_POST_PROCESSING = 6
    IMAGE_POST_PROCESSING_COMPLETE = 7
    EXPORTING = 8
    EXPORT_COMPLETE = 9
    FAILED = 10
    DELETED = 11
