title: SlideTap
description: Pathology data extraction and curation
theme: just-the-docs

url: https://imi-bigpicture.github.io/slidetap

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
